In [2]:
#adds in imports and changes working directory 

from PIL import Image
import os 
from PIL import ImageFilter
import imageio
import cv2
import skimage
import numpy as np
import matplotlib
from skimage.viewer import ImageViewer

#os.getcwd() #get current working directory 
#copy path: Documents/Duke University/Research/_HBEF/CameraTrapAnalysis/hbwater_cameratrap_pheno/
%cd "C:/Users/Thell/Documents/Duke University/Research/_HBEF/CameraTrapAnalysis/hbwater_cameratrap_pheno"

C:\Users\Thell\Documents\Duke University\Research\_HBEF\CameraTrapAnalysis\hbwater_cameratrap_pheno


In [7]:
#load in mask, invert mask 
ROI_name = 'W6 Channel Oct-Dec 2018_RF_0002_02.tif'
mask = imageio.imread('data_raw/W6 Channel Oct-Dec 2018/ROI/' + ROI_name)                                                         

# Change 1s to 0s and 0s to 1s
mask = 255 - mask          
imageio.imwrite("data_raw/W6 Channel Oct-Dec 2018/ROI/invertedmask_1.tif", mask) # we may not need to save results
mask2 = cv2.imread('data_raw/W6 Channel Oct-Dec 2018/ROI/invertedmask_1.tif',0)
# Save result and re-load into the proper format 

In [8]:
print(mask2) #ensure mask worked 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
#create folder to hold masked images 

ROI_id = 'W6_channel_top2018'
path = 'data_der/' + ROI_id

try:
    os.mkdir(path)
except OSError:
    print ("Creation of the directory %s failed" % path)
else:
    print ("Successfully created the directory %s " % path)

Successfully created the directory data_der/W6_channel_top2018 


In [10]:
#make masked images in for-loop
folder = "W6 Channel Oct-Dec 2018"
outfolder = "W6_channel_top2018"
def main(): 
    # path of the folder containing the raw images 
    inPath ="data_raw/" + folder
  
    # path of the folder that will contain the modified image 
    outPath ="data_der/" + outfolder
  
    for imagePath in [fn for fn in os.listdir(inPath)
              if fn.endswith('.JPG')]: 
        # imagePath contains name of the image  
        #imagePath = os.listdir(inPath)
        inputPath = os.path.join(inPath, imagePath) 
  
        # inputPath contains the full directory name 
        img = skimage.io.imread(inputPath)

        fullOutPath = os.path.join(outPath, 'invert_'+imagePath) 
        # fullOutPath contains the path of the output 
        # image that needs to be generated 
        res = cv2.bitwise_and(img, img, mask = mask2)
        #img.rotate(90).save(fullOutPath) 
        imageio.imwrite(fullOutPath,res)

        print(fullOutPath)
  
        #Driver Function 
if __name__ == '__main__': 
    main() 

data_der/W6_channel_top2018\invert_Hbwtr_w6_20181013_120459.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181014_120456.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181015_115953.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181016_120450.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181017_115947.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181018_120443.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181019_115940.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181020_115937.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181021_115934.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181022_115931.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181023_115928.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181024_120424.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181025_115921.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181026_115918.JPG
data_der/W6_channel_top2018\invert_Hbwtr_w6_20181027_120415.JPG
data_der/W6_channel_top2018\invert_Hbwtr