In [47]:
#adds in imports and changes working directory 

from PIL import Image
import os 
from PIL import ImageFilter
import imageio
import cv2
import skimage
import numpy as np
import matplotlib
from skimage.viewer import ImageViewer
import pandas as pd
from datetime import datetime


#os.getcwd() #get current working directory 
#copy path: Documents/Duke University/Research/_HBEF/CameraTrapAnalysis/hbwater_cameratrap_pheno/
%cd "C:/Users/Thell/Documents/Duke University/Research/_HBEF/CameraTrapAnalysis/hbwater_cameratrap_pheno"

C:\Users\Thell\Documents\Duke University\Research\_HBEF\CameraTrapAnalysis\hbwater_cameratrap_pheno


In [53]:
#load in mask, invert mask 
folder = 'W3 GC Channel 2-5-19 thru 12-31-19'#change here
ROI_name = 'W3 GC Channel 5-5-19 thru 12-31-19_RF_0002_02.tif' #change here
mask = imageio.imread('data_raw/' + folder + '/ROI/' + ROI_name)                                                         

# Change 1s to 0s and 0s to 1s
mask = 255 - mask          
imageio.imwrite('data_raw/' + folder + '/ROI/invertedmask.tif', mask) # we may not need to save results
mask2 = cv2.imread('data_raw/' + folder + '/ROI/invertedmask.tif',0)
# Save result and re-load into the proper format 

In [54]:
print(mask2) #ensure mask worked 

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [55]:
#create folder to hold masked images 

ROI_id = 'hbwtr_w3_5-5-19 thru 12-31-19' #change here
path = 'data_der/' + ROI_id

try:
    os.mkdir(path)
except OSError:
    print ("Creation of the directory %s failed" % path)
else:
    print ("Successfully created the directory %s " % path)

Successfully created the directory data_der/hbwtr_w3_5-5-19 thru 12-31-19 


In [56]:
#make masked images in for-loop
#folder = "W6 Channel Oct-Dec 2018"
#outfolder = "W6_channel_top2018"
def main(): 
    # path of the folder containing the raw images 
    inPath ="data_raw/" + folder
  
    # path of the folder that will contain the modified image 
    outPath ="data_der/" + ROI_id
    
    # add date ranges for R
    dates = pd.date_range(start="2019-05-05",end="2019-12-31") #change here 
    date_list = dates.strftime('%Y%m%d').tolist()
  
  #  for imagePath in [fn for fn in os.listdir(inPath)
            #  if fn.endswith('.JPG')]: 
    for imagePath in os.listdir(inPath):
        for date in date_list:
            if date in imagePath:   
    
        # imagePath contains name of the image  
        #imagePath = os.listdir(inPath)
                inputPath = os.path.join(inPath, imagePath) 

                # inputPath contains the full directory name 
                img = skimage.io.imread(inputPath)

                fullOutPath = os.path.join(outPath, 'invert_'+imagePath) 
                # fullOutPath contains the path of the output 
                # image that needs to be generated 
                res = cv2.bitwise_and(img, img, mask = mask2)
                #img.rotate(90).save(fullOutPath) 
                imageio.imwrite(fullOutPath,res)

                print(fullOutPath)
  
        #Driver Function 
if __name__ == '__main__': 
    main() 

data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190505_115955.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190506_115955.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190507_115954.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190508_115954.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190509_115953.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190510_115953.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190511_115952.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190512_115952.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190513_115951.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190514_115951.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190515_115950.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190516_115950.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190517_115950.JPG
data_der/hbwtr_w3_5-5-19 

data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190822_120355.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190823_115855.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190824_115854.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190825_115854.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190826_115853.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190827_115853.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190828_115852.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190829_115852.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190830_115851.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190831_115851.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190901_115850.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190902_115850.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20190903_115849.JPG
data_der/hbwtr_w3_5-5-19 

data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191210_120001.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191211_120001.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191212_120000.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191213_120000.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191214_115959.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191215_115959.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191216_115958.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191217_115958.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191218_115958.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191219_115957.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191220_115957.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191221_115956.JPG
data_der/hbwtr_w3_5-5-19 thru 12-31-19\invert_Hbwtr_w3_20191222_115956.JPG
data_der/hbwtr_w3_5-5-19 